apiVersion: v1
kind: Secret
metadata:
  name: photostudio-secret
  namespace: photostudio-ns
type: Opaque
stringData:
  MONGODB_AUTH_URI: mongodb://mongo:27017/artgallery
  MONGODB_FEEDBACK_URI: mongodb://mongo:27017/artgallery
  MONGODB_URI: mongodb://mongo:27017
